name: flutter_ble_lib
description: FlutterBle Library is a flutter library that supports BLE operations. It uses MultiPlatformBleAdapter as a native backend..
version: 2.4.1
homepage: https://github.com/Polidea/FlutterBleLib

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.15.0
  async: ^2.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.0.3
  build_runner: ^2.4.12
  pedantic: ^1.11.0

  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.polidea.flutter_ble_lib
        pluginClass: FlutterBleLibPlugin
      ios:
        pluginClass: FlutterBleLibPlugin
